version: '2'
services:
  some-mongo:
    image: "mongo:latest"
    volumes:
      - /home/konstantin/work/docker/dckr-graylog2/data/mongo:/data/db

  some-elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.5.1"
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=graylog
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - /home/konstantin/work/docker/dckr-graylog2/data/elasticsearch:/usr/share/elasticsearch/data

  graylog:
    image: "graylog2/server:latest"
    volumes:
      - /home/konstantin/work/docker/dckr-graylog2/data/journal:/usr/share/graylog/data/journal
      - /home/konstantin/work/docker/dckr-graylog2/config:/usr/share/graylog/data/config
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: /api
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch:9200/
    links:
      - some-mongo:mongo
      - some-elasticsearch:elasticsearch
    depends_on:
      - some-mongo
      - some-elasticsearch
    ports:
      - "9000:9000"
      - "9200:9200"
      - "1514:514/tcp"
      - "1514:514/udp"
      - "12201:12201/tcp"
      - "12201:12201/udp"
      - "12221:12221/tcp"
      - "12221:12221/udp"
# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local



version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
  mongo:
    image: "mongo:4.2"
    # Other settings [...]
  elasticsearch:
    image: "elasticsearch:7.9.2"
    # Other settings [...]
  graylog:
    image: graylog/graylog:4.2
    # Other settings [...]
    ports:
      - "9000:9000"
      - "12201:12201"
      - "1514:1514"
    environment:
      GRAYLOG_TRANSPORT_EMAIL_ENABLED: "true"
      GRAYLOG_TRANSPORT_EMAIL_HOSTNAME: smtp
      GRAYLOG_TRANSPORT_EMAIL_PORT: 25
      GRAYLOG_TRANSPORT_EMAIL_USE_AUTH: "false"
      GRAYLOG_TRANSPORT_EMAIL_USE_TLS: "false"
      GRAYLOG_TRANSPORT_EMAIL_USE_SSL: "false"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
      GRAYLOG_PASSWORD_SECRET: "yESMn44eQlUXTqN2RyXqJzbxatiHZwGZwWJu9pUHNOQAQQm1NmKiQwtk7l5u6pC0m7ub6ilyFh0YqepA9"
      GRAYLOG_ROOT_PASSWORD_SHA2: "65e84be33532fb784c48129675f9eff3a682b27168c0ea744b2cf58ee02337c5"
