// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pbsun

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SunClient is the client API for Sun service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SunClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Test, error)
}

type sunClient struct {
	cc grpc.ClientConnInterface
}

func NewSunClient(cc grpc.ClientConnInterface) SunClient {
	return &sunClient{cc}
}

func (c *sunClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Test, error) {
	out := new(Test)
	err := c.cc.Invoke(ctx, "/pbsun.Sun/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SunServer is the server API for Sun service.
// All implementations must embed UnimplementedSunServer
// for forward compatibility
type SunServer interface {
	Ping(context.Context, *emptypb.Empty) (*Test, error)
	mustEmbedUnimplementedSunServer()
}

// UnimplementedSunServer must be embedded to have forward compatible implementations.
type UnimplementedSunServer struct {
}

func (UnimplementedSunServer) Ping(context.Context, *emptypb.Empty) (*Test, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSunServer) mustEmbedUnimplementedSunServer() {}

// UnsafeSunServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SunServer will
// result in compilation errors.
type UnsafeSunServer interface {
	mustEmbedUnimplementedSunServer()
}

func RegisterSunServer(s grpc.ServiceRegistrar, srv SunServer) {
	s.RegisterService(&Sun_ServiceDesc, srv)
}

func _Sun_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SunServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbsun.Sun/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SunServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Sun_ServiceDesc is the grpc.ServiceDesc for Sun service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sun_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbsun.Sun",
	HandlerType: (*SunServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Sun_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types/pbsun/service.proto",
}
