// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pbsun

import (
	context "context"

	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PbsunClient is the client API for Pbsun service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PbsunClient interface {
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Test, error)
}

type pbsunClient struct {
	cc grpc.ClientConnInterface
}

func NewPbsunClient(cc grpc.ClientConnInterface) PbsunClient {
	return &pbsunClient{cc}
}

func (c *pbsunClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Test, error) {
	out := new(Test)
	err := c.cc.Invoke(ctx, "/pbsun.Pbsun/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PbsunServer is the server API for Pbsun service.
// All implementations must embed UnimplementedPbsunServer
// for forward compatibility
type PbsunServer interface {
	Ping(context.Context, *empty.Empty) (*Test, error)
	mustEmbedUnimplementedPbsunServer()
}

// UnimplementedPbsunServer must be embedded to have forward compatible implementations.
type UnimplementedPbsunServer struct {
}

func (UnimplementedPbsunServer) Ping(context.Context, *empty.Empty) (*Test, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPbsunServer) mustEmbedUnimplementedPbsunServer() {}

// UnsafePbsunServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PbsunServer will
// result in compilation errors.
type UnsafePbsunServer interface {
	mustEmbedUnimplementedPbsunServer()
}

func RegisterPbsunServer(s grpc.ServiceRegistrar, srv PbsunServer) {
	s.RegisterService(&Pbsun_ServiceDesc, srv)
}

func _Pbsun_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbsunServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbsun.Pbsun/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbsunServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Pbsun_ServiceDesc is the grpc.ServiceDesc for Pbsun service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pbsun_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbsun.Pbsun",
	HandlerType: (*PbsunServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Pbsun_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types/pbsun/service.proto",
}
