// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package mdsample

var TableNames = struct {
	GooseDBVersion string
	MinioST        string
	Orders         string
	Roles          string
	Users          string
	UsersRoles     string
}{
	GooseDBVersion: "goose_db_version",
	MinioST:        "minio_st",
	Orders:         "orders",
	Roles:          "roles",
	Users:          "users",
	UsersRoles:     "users_roles",
}
