basePath: /
definitions:
  mdsample.User:
    properties:
      alias:
        items:
          type: string
        type: array
      cnt:
        type: integer
      cnt2:
        type: integer
      cnt4:
        type: integer
      cnt8:
        type: integer
      created_at:
        example: "2006-01-02T15:04:05Z"
        type: string
      data:
        example: BYTES
        type: string
      deleted_at:
        example: "2006-01-02T15:04:05Z"
        type: string
      description:
        type: string
      duration:
        example: 0
        type: number
      id:
        example: 8ca3c9c3-cf1a-47fe-8723-3f957538ce42
        type: string
      is_online:
        type: boolean
      login:
        type: string
      metrika:
        example: JSON
        type: string
      price:
        example: 0.01
        type: number
      summa_one:
        example: 0.01
        type: number
      summa_two:
        example: 0.01
        type: number
      updated_at:
        example: "2006-01-02T15:04:05Z"
        type: string
    type: object
info:
  contact:
    email: konstantin@shamiev.ru
    name: API Support
  description: Sungora
  license:
    name: Sample License
  termsOfService: http://swagger.io/terms/
  title: Sungora API
  version: 1.0.0
paths:
  /api/sun/general/file/upload:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: загружаемый файл
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: загрузка файла на сервер
      tags:
      - General
  /api/sun/general/ping:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping
      tags:
      - General
  /api/sun/general/version:
    get:
      responses:
        "200":
          description: version
          schema:
            type: string
      summary: получение версии приложения
      tags:
      - General
  /api/sun/user-test/{id}:
    get:
      consumes:
      - application/json
      deprecated: true
      description: Тестовый обработчик для примера
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: пользователь
          schema:
            $ref: '#/definitions/mdsample.User'
        "400":
          description: отрицательный ответ
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Тестовый обработчик для примера
      tags:
      - User
  /api/sun/user/{id}:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Удаление пользователя
      tags:
      - User
    get:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mdsample.User'
      summary: Получение пользователя
      tags:
      - User
    post:
      parameters:
      - description: пользователь
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/mdsample.User'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mdsample.User'
      summary: Создание пользователя
      tags:
      - User
    put:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      - description: пользователь
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/mdsample.User'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mdsample.User'
      summary: Изменение пользователя
      tags:
      - User
  /api/sun/users:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/mdsample.User'
              type: array
            type: array
      summary: Получение списка пользователей
      tags:
      - User
  /api/sun/websocket/gorilla/{id}:
    get:
      responses:
        "101":
          description: Switching Protocols to websocket
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: пример работы с веб-сокетом (http://localhost:8080/template/gorilla/index.html)
      tags:
      - Websocket
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- description: Общие запросы
  name: General
- description: Пользователи
  name: User
- description: Чат (веб сокет)
  name: Websocket
