// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pbsungora

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SungoraClient is the client API for Sungora service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SungoraClient interface {
	Ping(ctx context.Context, in *Test, opts ...grpc.CallOption) (*Test, error)
}

type sungoraClient struct {
	cc grpc.ClientConnInterface
}

func NewSungoraClient(cc grpc.ClientConnInterface) SungoraClient {
	return &sungoraClient{cc}
}

func (c *sungoraClient) Ping(ctx context.Context, in *Test, opts ...grpc.CallOption) (*Test, error) {
	out := new(Test)
	err := c.cc.Invoke(ctx, "/pbsungora.Sungora/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SungoraServer is the server API for Sungora service.
// All implementations must embed UnimplementedSungoraServer
// for forward compatibility
type SungoraServer interface {
	Ping(context.Context, *Test) (*Test, error)
	mustEmbedUnimplementedSungoraServer()
}

// UnimplementedSungoraServer must be embedded to have forward compatible implementations.
type UnimplementedSungoraServer struct {
}

func (UnimplementedSungoraServer) Ping(context.Context, *Test) (*Test, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSungoraServer) mustEmbedUnimplementedSungoraServer() {}

// UnsafeSungoraServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SungoraServer will
// result in compilation errors.
type UnsafeSungoraServer interface {
	mustEmbedUnimplementedSungoraServer()
}

func RegisterSungoraServer(s grpc.ServiceRegistrar, srv SungoraServer) {
	s.RegisterService(&Sungora_ServiceDesc, srv)
}

func _Sungora_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Test)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SungoraServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbsungora.Sungora/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SungoraServer).Ping(ctx, req.(*Test))
	}
	return interceptor(ctx, in, info, handler)
}

// Sungora_ServiceDesc is the grpc.ServiceDesc for Sungora service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sungora_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbsungora.Sungora",
	HandlerType: (*SungoraServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Sungora_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pbsungora/sungora.proto",
}
